server:
  port: 9769
  servlet:
    session:
      timeout: 1s
  tomcat.uri-encoding: utf-8
spring:
  application:
    name: service-zuul
  cloud:
    consul:
      host: 202.135.136.120
      port: 8500
      discovery:
        serviceName: service-zuul
        register: true
        tags: version=1.0,author=liuzw
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        prefer-ip-address: true
  datasource:
    url: jdbc:mysql://202.135.136.180:3306/apiManager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: jn2018.
    driver-class-name: com.mysql.jdbc.Driver
zuul:
  ignoredServices: '*'
  routes:
    account:
      path: /account/**
      serviceId: ISP_ACCOUNTSERVICE
    action:
      path: /action/**
      serviceId: ISP_ACTIONSERVICE
    cent:
      path: /cent/**
      serviceId: ISP_CENTSERVICE
    cas:
      path: /cas/**
      serviceId: unifiedAuthentication
    authentication:
      path: /authentication/**
      serviceId: authenticationMS
    order:
      path: /order/**
      serviceId: ISP_ORDERSERVICE
    pay:
      path: /pay/**
      serviceId: ISP_PAYMENTSERVICE



mybatis:
  mapper-locations: classpath:sqlclient/*.xml

logging:
  level:
    root: debug
  path: /main/apps/
  file: zuul.log
