#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:9761/eureka/
server:
  port: 9769
  session-timeout: 30
  tomcat.uri-encoding: utf-8
spring:
  application:
    name: service-zuul
  cloud:
    consul:
      host: 202.135.136.120
      port: 8500
      discovery:
        serviceName: service-zuul
  datasource:
    #    url: jdbc:mysql://202.135.136.180:3306/securityDB?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://202.135.136.180:3306/apiManager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: jn2018.
    driver-class-name: com.mysql.jdbc.Driver
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: service-ribbon
    api-b:
      path: /api/b/**
      serviceId: service-feign
    api-c:
      path: /api-c/**
      serviceId: ACCOUNTSERVICE

mybatis:
  mapper-locations: classpath:sqlclient/*.xml

logging:
  level:
    root: debug
